// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable-copy-shortcut": boolean;
      "manually-launch-executable-file": boolean;
      "copy-shortcut": string;
    };
  }
}
